replicaCount: 1

image:
  repository: ghcr.io/renatovassao/devops-poc
  pullPolicy: IfNotPresent
  tag: "main"

service:
  type: ClusterIP
  port: 3000

env:
  - name: REDIS_HOST
    value: "redis"
  - name: REDIS_PORT
    value: "6379"
  - name: PGHOST
    value: "postgres"
  - name: PGPORT
    value: "5432"
  - name: PGUSER
    value: "postgres"
  - name: PGPASSWORD
    value: "postgres"

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /readyz
    port: http